### ISSUE TITLE
how to generate mxnet_predict-all.cc

### ISSUE THREAD

**Issue by PetroWu** [dneprDroid/ImageRecognizer#1]
Thank you for your work! I've tried to generate mx_predict-all.cc with mxnet on mac 10.12 by following the instructions of the fresh clone v0.9.3. But there's lots of compile errors when i copied it to WhatIsThis-ios projects. I wonder if you set some configuration of mxnet? Could you  please provide the processes to generate mxnet_predict-all.cc?
Thank you very much!

**Comment by dneprDroid** [comment]
See this branch with upgraded MXNet sources in my repository: https://github.com/dneprDroid/ImageRecognizer-iOS/tree/upgrade_mxnet

Useful guide for MXNet compiling:  http://www.liuxiao.org/2015/12/ios-mxnet-%E7%9A%84-ios-%E7%89%88%E6%9C%AC%E7%BC%96%E8%AF%91/ 

In ios version don't forget to add Accelerate framework to your xcode project.

**Comment by PetroWu** [comment]
Thank you for your quick reply!
